import { AnalysedRule, ExportData, ExportMeta } from "@/types"
import getCSPOverview from "./csp-overview";
import buildAttackSurface from "./attack-surface";



export const generateExportData = (rules: AnalysedRule[], meta: ExportMeta): ExportData => {
  const overview = getCSPOverview(rules);
  const attackSurface = buildAttackSurface(rules);

  return {
    meta,
    overview: {
      policyGrade: overview.policyGrade,
      summary: {
        directivesPresent: overview.count,
        missingCritical: overview.missingDirectives.length,
        redFlagCount: overview.redFlags.length
      }
    },
    findings: {
        missingDirectives: overview.missingDirectives,
        redFlags: overview.redFlags
    },
    attackSurface,
    policy: rules
  }
}


export const generateMDExport = (data: ExportData): string => {
  let md = "";

  // ------------------ HEADER --------------------
  md += `# CSP Analysis Report\n\n`
  md += `**Generated by:** CSPLens - [csplens.pratiksingh.xyz](https://csplens.pratiksingh.xyz)  \n`
  md += `**Generated at:** ${new Date(data.meta.generatedAt).toLocaleString()}  \n`
  md += `**Input type:** ${data.meta.input.source}  \n`

  if (data.meta.input.source === "fetched-url") {
    md += `**URL:** ${data.meta.input.url}  \n`
  }

  md += `**Report only:** ${data.meta.input.reportOnly ? "Yes" : "No"}  \n`
  md += `\n---\n\n`


  // ----------------- OVERVIEW --------------------
  md += `## Overview\n\n`
  md += `**Policy grade:** ${data.overview.policyGrade.grade}  \n`
  md += `**Score:** ${data.overview.policyGrade.score}/100  \n`
  if (data.overview.policyGrade.cappedBy) {
    md += `**Grade capped by:** ${data.overview.policyGrade.cappedBy}  \n`
  }
  md += "\n"

  // ----------------- MISSING DIRECTIVES ---------------
  if (data.overview.summary.missingCritical > 0) {
    md += `## Missing Directives (${data.overview.summary.missingCritical})\n\n`
    for (const m of data.findings.missingDirectives) {
      md += `- **${m.directive}** (${m.importance})\n`
      md += `  - Recommendation: ${m.recommendation}\n`
      md += `  - Suggested rule: \`${m.recommendedRule}\`\n`
      if(m.references) {
        md += `  - Reference: [${m.references?.label}](${m.references?.url})\n`
      }
    }
    md += '\n'
  }

  // ---------------- RED FLAGS -----------------------
  if (data.overview.summary.redFlagCount > 0) {
    md += `## Red Flags (${data.overview.summary.redFlagCount})\n\n`
    for (const r of data.findings.redFlags) {
      md += `- **${r.key}** (${r.level})\n`
      md += `  - Reason: ${r.reason}\n`
      if(r.recommendation) {
        md += `  - Recommendation: ${r.recommendation}\n`
      }
      md += `  - Affected Directives: ${r.directives.join(", ")}\n`
      if (r.references) {
        md += `  - Reference: [${r.references?.label}](${r.references?.url})\n`
      }
    }
    md += `\n`
  }

  // ---------------- ATTACK SURFACE -----------------
  md += `## Attack Surface\n\n`
  if (data.attackSurface.length === 0) {
    md += `No significant attack vector detected.\n\n`
  } else {
    for (const a of data.attackSurface) {
      md += `### ${a.title}\n`
      md += `**Severity:** ${a.severity}\n\n`
      md += `${a.impact}\n\n`
      md += `**Causes:**\n`

      for (const c of a.causes) {
        md += `- \`${c.directive}: ${c.source}\`\n`
      }
    }
    md += "\n"
  }

  // --------------- POLICY BREAKDOWN ---------------
  md += `## Policy Breakdown (${data.overview.summary.directivesPresent})\n\n`
  for (const r of data.policy) {
    md += `### ${r.directive}\n`
    for (const src of r.sources) {
      md += `- \`${src.source.value}\` — `
      md += `\`${src.source.kind}\` — `
      md += `${src.level}\n`

      md += `  - ${src.reason}\n`
      if (src.recommendation) {
        md += `  - Recommendation: ${src.recommendation}\n`
      }
    }
    
    md += `\n`
  }

  return md;
}



